services:
  flask_app:
    container_name: flask_app
    build: .
    ports:
      - "4000:4000"
      - "5678:5678"
    volumes:
      - .:/app
    environment:
      - DB_URL=postgresql://flask_test:flask_test@flask_db:5432/flask_test_db
      - REDIS_URL=flask_redis
      - JWT_SECRET=Secret-Key
    depends_on:
      - flask_db
      - flask_redis
  flask_db:
    container_name: flask_db
    image: postgres:15
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=flask_test
      - POSTGRES_USER=flask_test
      - POSTGRES_DB=flask_test_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  flask_redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata: {}
